//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ressources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Array.
        /// </summary>
        public static string AdminArray {
            get {
                return ResourceManager.GetString("AdminArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days a week.
        /// </summary>
        public static string DaysAweek {
            get {
                return ResourceManager.GetString("DaysAweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Profile.
        /// </summary>
        public static string DefaultProfile {
            get {
                return ResourceManager.GetString("DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default settings for all employees.
        /// </summary>
        public static string DefaultSettingsForAllEmployees {
            get {
                return ResourceManager.GetString("DefaultSettingsForAllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Project?.
        /// </summary>
        public static string deletePrWarning {
            get {
                return ResourceManager.GetString("deletePrWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezember.
        /// </summary>
        public static string Dezember {
            get {
                return ResourceManager.GetString("Dezember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Work.
        /// </summary>
        public static string EndWork {
            get {
                return ResourceManager.GetString("EndWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the Project responsible name..
        /// </summary>
        public static string errProjectResponsible {
            get {
                return ResourceManager.GetString("errProjectResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the Projects&apos;s name.
        /// </summary>
        public static string errProjName {
            get {
                return ResourceManager.GetString("errProjName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours in a day.
        /// </summary>
        public static string HoursAday {
            get {
                return ResourceManager.GetString("HoursAday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours a week.
        /// </summary>
        public static string HoursAweek {
            get {
                return ResourceManager.GetString("HoursAweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juni.
        /// </summary>
        public static string Juni {
            get {
                return ResourceManager.GetString("Juni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai.
        /// </summary>
        public static string Mai {
            get {
                return ResourceManager.GetString("Mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months a year.
        /// </summary>
        public static string MonthsAyear {
            get {
                return ResourceManager.GetString("MonthsAyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New project.
        /// </summary>
        public static string newProject {
            get {
                return ResourceManager.GetString("newProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Wirk Time fpr today.
        ///   Looks up a localized string similar to New Work Time for.
        /// </summary>
        public static string NewWorkTime {
            get {
                return ResourceManager.GetString("NewWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project responsible.
        /// </summary>
        public static string ProjectResponsible {
            get {
                return ResourceManager.GetString("ProjectResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause in min..
        /// </summary>
        public static string PauseInMin {
            get {
                return ResourceManager.GetString("PauseInMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Illness.
        /// </summary>
        public static string ReportIllness {
            get {
                return ResourceManager.GetString("ReportIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Holoday.
        /// </summary>
        public static string RequestHoloday {
            get {
                return ResourceManager.GetString("RequestHoloday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartWork {
            get {
                return ResourceManager.GetString("StartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Work Now.
        /// </summary>
        public static string StartWorkNow {
            get {
                return ResourceManager.GetString("StartWorkNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time tracking for month.
        /// </summary>
        public static string UserHeader {
            get {
                return ResourceManager.GetString("UserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacation days.
        /// </summary>
        public static string VacationDays {
            get {
                return ResourceManager.GetString("VacationDays", resourceCulture);
            }
        }
    }
}
